/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Database.Database;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author joelandrew
 */
public class Editprofile extends javax.swing.JFrame {

    /**
     * Creates new form Editprofile
     */
    public Editprofile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbSave = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        txNama = new javax.swing.JTextField();
        txNIM = new javax.swing.JTextField();
        txAlamat = new javax.swing.JTextField();
        txNoHP = new javax.swing.JTextField();
        txEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jxDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jbSave.setText("Save");
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jbSave);
        jbSave.setBounds(209, 248, 57, 23);

        jbCancel.setText("Cancel");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jbCancel);
        jbCancel.setBounds(117, 248, 65, 23);
        jPanel1.add(txNama);
        txNama.setBounds(117, 49, 263, 20);

        txNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNIMActionPerformed(evt);
            }
        });
        jPanel1.add(txNIM);
        txNIM.setBounds(117, 81, 263, 20);
        jPanel1.add(txAlamat);
        txAlamat.setBounds(117, 152, 263, 20);
        jPanel1.add(txNoHP);
        txNoHP.setBounds(117, 184, 263, 20);
        jPanel1.add(txEmail);
        txEmail.setBounds(117, 216, 263, 20);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Hoefler Text", 1, 13)); // NOI18N
        jLabel1.setText("Nama");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 54, 50, 18);

        jLabel2.setFont(new java.awt.Font("Hoefler Text", 1, 13)); // NOI18N
        jLabel2.setText("Tanggal Lahir");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 124, 100, 18);

        jLabel3.setFont(new java.awt.Font("Hoefler Text", 1, 13)); // NOI18N
        jLabel3.setText("Alamat");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 157, 60, 18);

        jLabel4.setFont(new java.awt.Font("Hoefler Text", 1, 13)); // NOI18N
        jLabel4.setText("No HP");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 189, 50, 18);

        jLabel5.setFont(new java.awt.Font("Hoefler Text", 1, 13)); // NOI18N
        jLabel5.setText("E-mail");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 221, 60, 18);

        jLabel6.setFont(new java.awt.Font("Hoefler Text", 1, 13)); // NOI18N
        jLabel6.setText("NIM");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 86, 50, 18);

        jLabel7.setFont(new java.awt.Font("Krungthep", 1, 13)); // NOI18N
        jLabel7.setText("EDIT PROFIL");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(157, 15, 90, 18);

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 40, 30, 270);

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 390, 42);
        jPanel1.add(jxDate);
        jxDate.setBounds(120, 120, 120, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Screen Shot 2017-11-30 at 13.24.38.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 40, 370, 270);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNIMActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSaveActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbSave;
    private org.jdesktop.swingx.JXDatePicker jxDate;
    private javax.swing.JTextField txAlamat;
    private javax.swing.JTextField txEmail;
    private javax.swing.JTextField txNIM;
    private javax.swing.JTextField txNama;
    private javax.swing.JTextField txNoHP;
    // End of variables declaration//GEN-END:variables

    public JButton getJbCancel() {
        return jbCancel;
    }

    public JButton getJbSave() {
        return jbSave;
    }

    public Date getJxDate() {
        return jxDate.getDate();
    }

    public String getTxAlamat() {
        return txAlamat.getText();
    }

    public String getTxEmail() {
        return txEmail.getText();
    }

    public String getTxNama() {
        return txNama.getText();
    }

    public String getTxNoHP() {
        return txNoHP.getText();
    }

    public void setTxNIM() {
        txNIM.setEditable(false);
        this.txNIM.setText(Database.NIM);
    }
    
    public void setActionListener(ActionListener a){
        jbCancel.addActionListener(a);
        jbSave.addActionListener(a);
     }
    
    public void ShowMessage(String m){
        JOptionPane.showMessageDialog(this, m);
    }
    
}
